export type Brand = {
  name: string;
  file: string;
};

/**
 * The manufacturers Mariot represents. Shared by the homepage marquee and the
 * /brands directory so the two can never fall out of step; the logo files live
 * in /public/brands.
 */
export const BRANDS: Brand[] = [
  { name: '3MF', file: '3mf.webp' },
  { name: 'Ailipu', file: 'ailipu-1.webp' },
  { name: 'Alto-Shaam', file: 'Alto-Shaam.webp' },
  { name: 'Anfim', file: 'anfilm.webp' },
  { name: 'APW Wyott', file: 'apwwyott.webp' },
  { name: 'Asaki', file: 'asaki-logo.webp' },
  { name: 'Battistella', file: 'BATTISTELLA-1.webp' },
  { name: 'Berjaya', file: 'Berjaya-Logo.webp' },
  { name: 'Bilait', file: 'BILAIT-Logo.webp' },
  { name: 'Bimatic', file: 'bimatic.webp' },
  { name: 'Blendtec', file: 'Blendec-logo.webp' },
  { name: 'Brema', file: 'brema.webp' },
  { name: 'Bunn', file: 'bunn.webp' },
  { name: 'Camry', file: 'camry.webp' },
  { name: 'Capinox', file: 'capinox.webp' },
  { name: 'Cofrimell', file: 'cofrimell.webp' },
  { name: 'Desmon', file: 'desmon.webp' },
  { name: 'Easyline', file: 'easyline.webp' },
  { name: 'Electrolux', file: 'electrolux.webp' },
  { name: 'Empero', file: 'empero.webp' },
  { name: 'Fagor', file: 'FagorProfesional.webp' },
  { name: 'Ace Filters', file: 'Falater.webp' },
  { name: 'Fimar', file: 'fimar.webp' },
  { name: 'Frymaster', file: 'FRYMASTER.webp' },
  { name: 'Gelmatic', file: 'gelmatic.webp' },
  { name: 'GGF', file: 'ggf-logo.webp' },
  { name: 'GHS', file: 'ghs.webp' },
  { name: 'Grindmaster', file: 'grindmaster.webp' },
  { name: 'Hatco', file: 'hacto.webp' },
  { name: 'Hamilton Beach', file: 'hamilton-logo.webp' },
  { name: 'Henny Penny', file: 'hennypenny.webp' },
  { name: 'Hoonved', file: 'hoonved.webp' },
  { name: 'Hoshizaki', file: 'hoshizaki.webp' },
  { name: 'Imesa', file: 'imesa.webp' },
  { name: 'Imperial', file: 'IMPERIAL.webp' },
  { name: 'Infrico', file: 'inofrigo.webp' },
  { name: 'Josper', file: 'josper.webp' },
  { name: 'KitchenAid', file: 'Kitchen-Aid.webp' },
  { name: 'La Marzocco', file: 'La-Marzocco.webp' },
  { name: 'La Minerva', file: 'LA-MINERVA.webp' },
  { name: 'La Cimbali', file: 'lacimbali.webp' },
  { name: 'Miska', file: 'Logo-MiskaFoodTechnology1.webp' },
  { name: 'Longoni', file: 'Longoni-Brand.webp' },
  { name: 'Mac.Pan', file: 'macpac.webp' },
  { name: 'Mahlkonig', file: 'MAHLKONIG-vector-logo.webp' },
  { name: 'Mariot', file: 'mariot.webp' },
  { name: 'MBM', file: 'mbm-logo.webp' },
  { name: 'Menumaster', file: 'menumaster.webp' },
  { name: 'Merrychef', file: 'merrychef.webp' },
  { name: 'Middleby Marshall', file: 'middleby-marshall-logo.webp' },
  { name: 'MKE-Matic', file: 'mke-logo.webp' },
  { name: 'Moel', file: 'moel.webp' },
  { name: 'Monolith', file: 'monolith.webp' },
  { name: 'Mussana', file: 'mussana.webp' },
  { name: 'Nuova Simonelli', file: 'simonelli.webp' },
  { name: 'Omega', file: 'Omega.webp' },
  { name: 'Oztiryakiler', file: 'oztriyakiler.webp' },
  { name: 'Pastaline', file: 'pastaline.webp' },
  { name: 'Pitco', file: 'pitco.webp' },
  { name: 'POSLIX', file: 'poslix.webp' },
  { name: 'Prince Castle', file: 'prince-casle.webp' },
  { name: 'Rancilio', file: 'Rancilio-logo-1.webp' },
  { name: 'Rational', file: 'rational.webp' },
  { name: 'Red Fox', file: 'redfox.webp' },
  { name: 'Robot Coupe', file: 'robotcoupe.webp' },
  { name: 'Roller Grill', file: 'roller-grill.webp' },
  { name: 'Rotondi Group', file: 'Rotondi-Group.webp' },
  { name: 'SAB', file: 'sab.webp' },
  { name: 'Salva', file: 'salva.webp' },
  { name: 'Samixir', file: 'samixir.webp' },
  { name: 'Santos', file: 'santos.webp' },
  { name: 'SAP', file: 'sap-bone-saw-machine-in-dubai.webp' },
  { name: 'Scotsman', file: 'Logo-1.webp' },
  { name: 'Server', file: 'server.webp' },
  { name: 'Sheffield', file: 'Sheffiel.webp' },
  { name: 'Snooker', file: 'snooker-1.webp' },
  { name: 'Sofinor', file: 'sofinor.webp' },
  { name: 'Southbend', file: 'southbend.webp' },
  { name: 'Spaceman', file: '20210329_Spaceman-Logo_Black.webp' },
  { name: 'Speed Queen', file: 'Speed-Queen.webp' },
  { name: 'Star', file: 'star.webp' },
  { name: 'Stilco', file: 'stilco1.webp' },
  { name: 'Technocooler', file: 'technocooler.webp' },
  { name: 'Tecnodom', file: 'tecnodom.webp' },
  { name: 'Toastmaster', file: 'Toastmaster.webp' },
  { name: 'TurboChef', file: 'turbo-chef.webp' },
  { name: 'Ubermilk', file: 'uebermilk_logo_small.webp' },
  { name: 'Union', file: 'Union.webp' },
  { name: 'Unox', file: 'unox.webp' },
  { name: 'Venarro', file: 'venarro.webp' },
  { name: 'Venix', file: 'venix.webp' },
  { name: 'Vitamix', file: 'vitamix.webp' },
  { name: 'VITO', file: 'VITO-OIL-FILTER-SYSTEM.webp' },
  { name: 'Vulcan', file: 'VULCAN-BRAND.webp' },
  { name: 'Waring', file: 'warning.webp' },
  { name: 'Zemic Europe', file: 'Zemic-Europe.webp' },
  { name: 'Zmatik', file: 'zmatik-1.webp' },
  { name: 'Zumex', file: 'Zumex.webp' },
];
