// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";
import { getDatabaseUrl } from "./src/lib/dbConfig";

// Prisma's CLI only auto-loads a file named exactly ".env" — it doesn't know
// about .env.local or .env.live, so both are loaded explicitly here.
loadEnv({ path: process.env.NODE_ENV === "production" ? ".env.live" : ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Built from separate DB_HOST/DB_USER/DB_PASSWORD/DB_NAME/DB_PORT vars —
    // see src/lib/dbConfig.ts. Prisma's CLI specifically needs one URL
    // string here, unlike the app itself, which uses the config object form.
    url: getDatabaseUrl(),
  },
});
