// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { getDatabaseUrl } from "./src/lib/dbConfig";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Built from separate DB_HOST/DB_USER/DB_PASSWORD/DB_NAME/DB_PORT vars —
    // see src/lib/dbConfig.ts. Prisma's CLI specifically needs one URL
    // string here, unlike the app itself, which uses the config object form.
    url: getDatabaseUrl(),
  },
});
