// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Prisma's CLI only auto-loads a file named exactly ".env" — it doesn't know
// about .env.local or .env.live, so both are loaded explicitly here.
loadEnv({ path: process.env.NODE_ENV === "production" ? ".env.live" : ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
